from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.landing, name="landing" ),
    path("feed", views.index, name="index" ),
    path("user/<str:username>/", views.profile, name="profile"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("user/<str:username>/follow/", views.toggle_follow, name="toggle_follow"),
    path("post/<str:slug>", views.detail, name="detail"),
    path("post/<int:post_id>/like", views.toggle_like, name="toggle_like"),
    path("post/<int:post_id>/save", views.toggle_save, name="toggle_save"),
    path("post/<int:post_id>/comment", views.add_comment, name="add_comment"),
    path("new_something_url", views.new_url_view, name="new_page_url" ),
    path("old_url", views.old_url_redirect, name="old_url" ),
    path("contact/", views.contact, name="contact" ),
    path("terms/", views.terms_view, name="terms"),
    path("privacy/", views.privacy_view, name="privacy"),
    path("help/", views.help_view, name="help"),
    path("about", views.about, name="about" ),
    path("register", views.register, name="register" ),
    path("login", views.login, name="login" ),
    path("dashboard", views.dashboard, name="dashboard" ),
    path("logout", views.logout, name="logout" ),
    path("forgot_password", views.forgot_password, name="forgot_password" ),
    path("reset_password/<uidb64>/<token>", views.reset_password, name="reset_password" ),
    path("new_post", views.new_post, name="new_post" ),
    path("edit_post/<int:post_id>", views.edit_post, name="edit_post" ),
    path("delete_post/<int:post_id>", views.delete_post, name="delete_post" ),
    path("publish_post/<int:post_id>", views.publish_post, name="publish_post" ),
    path("admin-gateway/", views.admin_gateway, name="admin_gateway"),
    path("super-dashboard/", views.super_dashboard, name="super_dashboard"),
    path("super-dashboard/delete-post/<int:post_id>/", views.admin_delete_post, name="admin_delete_post"),
    path("super-dashboard/delete-user/<int:user_id>/", views.admin_delete_user, name="admin_delete_user"),
    path('api/generate_story/', views.generate_story, name='generate_story'),
    path('api/generate_image_proxy/', views.generate_image_proxy, name='generate_image_proxy'),
    path('search/', views.search, name='search'),
    path('user/<str:username>/accept_follow/', views.accept_follow, name='accept_follow'),
    path('user/<str:username>/decline_follow/', views.decline_follow, name='decline_follow'),
    path('messages/', views.inbox, name='inbox'),
    path('messages/<str:username>/', views.conversation, name='conversation'),
]